# Generated by Django 4.2.30 on 2026-07-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_epic_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
