# Generated by Django 4.2.30 on 2026-07-07 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_issueproperty_issuepropertyoption_issuepropertyvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepositoryMap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('repository_id', models.BigIntegerField(help_text='GitHub numeric repository id (stable across renames)')),
                ('full_name', models.CharField(help_text='"org/repo"', max_length=500)),
                ('installation_id', models.BigIntegerField(db_index=True, help_text='GitHub App installation id')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Github Repository Map',
                'verbose_name_plural': 'Github Repository Maps',
                'db_table': 'github_repository_maps',
                'ordering': ('-created_at',),
                'unique_together': {('repository_id', 'project', 'deleted_at')},
            },
        ),
        migrations.CreateModel(
            name='GithubPullRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pr_number', models.IntegerField()),
                ('repository_full_name', models.CharField(help_text='denormalized "org/repo" for display/link', max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=800)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('MERGED', 'Merged')], default='OPEN', max_length=30)),
                ('merged', models.BooleanField(default=False)),
                ('author_login', models.CharField(blank=True, max_length=255)),
                ('ephemeral_env_url', models.URLField(blank=True, max_length=800, null=True)),
                ('github_pr_id', models.BigIntegerField(blank=True, help_text='GitHub global PR id, for idempotent upsert', null=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_pull_requests', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('repository_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_requests', to='db.githubrepositorymap')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Github Pull Request',
                'verbose_name_plural': 'Github Pull Requests',
                'db_table': 'github_pull_requests',
                'ordering': ('-created_at',),
                'unique_together': {('issue', 'repository_full_name', 'pr_number', 'deleted_at')},
            },
        ),
    ]
